### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by mavam** [oscarlab/betrfs#2]
Do you plan on supporting FreeBSD in the future or will BetrFS exclusively remain a Linux endeavor?

**Comment by donporter** [comment]
We certainly don't object to supporting other OSes, including FreeBSD.  There is no fundamental reason for this project to be exclusively Linux.  If you or anyone else out there wants to work on a port, we'd love that and be happy to offer support.

All of the team's efforts are currently going into improving the core FS, so there are not any immediate plans to port to FreeBSD or other platforms.  We are working on getting BetrFS to run on unmodified Linux, which would probably make porting efforts easier.

**Comment by mavam** [comment]
That's good to hear. A porting effort would hopefully just integrate the betrfs abstractions into the OS-specific filesystem API and page cache.

The only political hindrance for a BSD port I could see is the GPL license. If at some point this becomes relevant, would you consider switching or perhaps dual-licensing your project?

**Comment by donporter** [comment]
I think porting would require adapting VFS/page cache abstractions, as well as adapting our "klibc" code.  The stacking on an underlying file system may take some effort.  Over time, we may streamline the klibc and stacking support, which would make this easier.

We aren't opposed to a dual/different license, but we derived our code from TokuDB, which is released under a modified GPL v2.  So my understanding is that we are constrained by that license.

**Comment by mavam** [comment]
Thanks for the info. I'll keep following the project and will get in touch when I can mobilize resources for a porting effort. Looking forward to see the project evolve.
