### ISSUE TITLE
Question about git benchmark for "File Systems Fated for Senescence? Nonsense, Says Science!"

### ISSUE THREAD

**Issue by xxks-kkk** [oscarlab/betrfs#7]
In "File Systems Fated for Senescence? Nonsense, Says Science!" paper section 6, there is a git benchmark

> We present a git benchmark that performs 10,000 pulls from the Linux git repository, starting from the initial commit. After every 100 pulls, the benchmark performs a recursive grep test and computes the file system’s dynamic layout score.

I assume the code for the benchmark code is under `benchmarks/aging/git/` directory. However, when I run the `test.py` after following the steps in README, I got the error:

```
000000 git pull --no-edit -s recursive -X theirs /home/iamzeyuanhu/hzy/linux 1da177e4c3f41524e886b7f1b8a0c1fc7321cac2
Traceback (most recent call last):
  File "test.py", line 236, in <module>
    stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'pull', '--no-edit', '-s', 'recursive', '-X', 'theirs', '/home/iamzeyuanhu/hzy/linux', '1da177e4c3f41524e886b7f1b8a0c1fc7321cac2']' returned non-zero exit status 1
```

Looking at the source code ([here](https://github.com/oscarlab/betrfs/blob/beac146663220ebc55173c53431950a91b628697/benchmarks/aging/git/test.py#L176)), I think `linux` mentioned in the line referred to the linux kernel repo that is clone before the benchmark (`test.py`) get invoked. Is this correct?

**Comment by aakshintala** [comment]
Yep, looks like there's a step missing in the README.
Looks like you need to clone the linux kernel in the same directory as test.py...

**Comment by ajhconway** [comment]
Hi Zeyuan,

Where are you running the benchmark from? The version in the betrfs repo
looks like it's out of date to me. Check out the version at
https://github.com/aineshbakshi/Git-Benchmark
and we'll update the betrfs one.

Best,
Alex

**Comment by ajhconway** [comment]
I've pushed the newer version to the betrfs repo as well now, so give that
a try. Please let us know if you have any problems and we'll try to help
out.

Best,
Alex

**Comment by xxks-kkk** [comment]
Thanks for the help! @aakshintala @ajhconway
